# Generated by Django 6.0.3 on 2026-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolVisit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
